# Railway Configuration for TeamPulse Turbo
[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/ready"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npm start"

[env]
NODE_ENV = "production"